### ISSUE TITLE
TypeError: Class constructor SqliteConnection cannot be invoked without 'new'

### ISSUE THREAD

**Issue by dbrgn** [juanluispaz/ts-sql-query#8]
I wanted to try the BetterSqlite3 example (in a separate project), but his fails already:

```typescript
// index.ts
import * as Sqlite from 'better-sqlite3';
import {SynchronousPromise} from 'synchronous-promise';
import {SqliteConnection} from 'ts-sql-query/connections/SqliteConnection';
import {BetterSqlite3QueryRunner} from 'ts-sql-query/queryRunners/BetterSqlite3QueryRunner';
import {ConsoleLogQueryRunner} from 'ts-sql-query/queryRunners/ConsoleLogQueryRunner';

const options: Sqlite.Options = { fileMustExist: true, readonly: false };
const db: Sqlite.Database = Sqlite('../test.db', options);

class DBConection extends SqliteConnection<'DBConnection'> {
}

const connection = new DBConection(new ConsoleLogQueryRunner(
    new BetterSqlite3QueryRunner(db, {promise: SynchronousPromise})));
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "strictNullChecks": true,
    "noImplicitAny": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

When running:

```
$ node_modules/.bin/ts-node index.ts
TypeError: Class constructor SqliteConnection cannot be invoked without 'new'
    at new DBConection (/media/veracrypt1/clients/web/ts-db-access-evaluation/ts-sql-query/index.ts:28:42)
    at Object.<anonymous> (/media/veracrypt1/clients/web/ts-db-access-evaluation/ts-sql-query/index.ts:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/media/veracrypt1/clients/web/ts-db-access-evaluation/ts-sql-query/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/media/veracrypt1/clients/web/ts-db-access-evaluation/ts-sql-query/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at main (/media/veracrypt1/clients/web/ts-db-access-evaluation/ts-sql-query/node_modules/ts-node/src/bin.ts:198:14)
```

Any ideas?

**Comment by juanluispaz** [comment]
Hi,

The issue is you are using a very old target (the default in typescript) that doesn't use class syntax, and ts-sql-query is transpiled using class syntax (long time supported by node). The way to fix it is by specifying the target property in your tsconfig.json as minimum `ES2015`.

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2020",
    "moduleResolution": "node",
    "strictNullChecks": true,
    "noImplicitAny": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by dbrgn** [comment]
Huh, strange, I could swear that I tried that before... Seems I did something wrong then, since it's helping indeed. Thanks a lot!
